### PR TITLE
Fix font issue

### LINKED ISSUE #1: Font not working
I be on a chromebook at school so the font wont load, fix this later as not everyone will/can install the `Gilroy` fonts.

### PR DESCRIPTION
**Pull request by akisblack**
probably fixes #1

### CODE REVIEW

**Comment by Odyssey346** [comment]
lmao @Oscie57 really?

**Comment by Oscie57** [comment]
This was being fixed on a local build, not needed

**Comment by Odyssey346** [comment]
Then push it to production.

**Comment by Oscie57** [comment]
I dont have access yet, its being worked on

**Comment by Oscie57** [comment]
Allow me to push local and then I will pull

**Comment by Oscie57** [comment]
@akisblack I need you to re-pull it.

**Comment by Oscie57** [comment]
wait, fixed in [`bebf3d2`](https://github.com/Oscie57/Oscie57.github.io/commit/bebf3d2907f91dd22d2bf76731fa1f670ce8900b)

**Pull request closed without merging**
